travis:
  secure:
    BINSTAR_TOKEN: dJzgQtwUt0IoEmaJAmHyvF7HVokvgvFJj02/jKVUHPdgXdL/e9/QfBvRljE7hjOj3++OdowaMZQfwCVnWNFIcqP1Ird03WZS/QlRPqjZIs22HNMBOunAnzBdSeG5n5IsrN70FJ6SkzdVF+HM9NzVMn5FE9sSW8JZdKhxoEhmrI8utKH0Xsqk1i0//HKvc9NEAzxzoS8BA/riELx9ri8VjgYJ1+uMP0NlrvkievmO4U7QSjBWd9bj1JKzqtMKRG2jpQo0KTAhvEGrFi6RaeB0Obo5NEIoYRd6Ik1T7gP59VMERt5dmCUis/L/1xHXgxo9oVT1hfre/2m4YxQULdh+ioLQQ+DAOb+/ZlzJ86raIf2vjRTORYAZRIN79FRPWkrWiVEFqOe4hEfoNJJEX3VRQs+UpAM8XbOMP3ihEvyy5spDvau7h2GdtTDLLb0u6Jcu0FpzGNvgDj1A2pUncHuryVUSGTq6KVFBsfjR6BVPVojo5/2bm1ZdNf+rIHvIUIoqoVFJSqU1gEqv+RGXlmDwBsbEMbhoPIZrhiTmcJvie8wfgIHlxfbPjtHMvS8ou+DO31CsiPrFm4GqBSGRgOXzDoqfHkNrgWtdEzUholf0ef9VEhJrKdcgKUg9uQJ83UuoSfy4etaxisKFMNuLUsBNyQ8xY5NFz38hcR+7YNxMO7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
